POST http://localhost:3000/api/region
Content-Type: application/json

{
    "name": "Fergana",
    "latitude": "40.37399148390805", 
    "longitude":"71.79903997366404"
}
###

GET http://localhost:3000/api/regions
